Composite
f-lab-edu/DesignPatternStudy pull request #5
Opened 2023-03-20 06:45 UTC by honggi123

2023-03-20 15:45 UTC, f-lab-paca requested changes
수고많으셨습니다.
다만, composite pattern을 적용하여 어떤 기능을 구현하려고 하신지 모르겠습니다.
printAll 함수 호출시 포함된 모든 파일 컴포넌트의 절대경로를 출력하도록 수정해보시겠어요?

root
ㄴ1.txt
ㄴsubA
    ㄴ a1.txt, a2.txt
ㄴsubB
    ㄴ b1.txt, b2.txt

위와 같은 구조일때 `root.printAll` 함수 호출시 아래 결과

root/1.txt
root/subA/a1.txt
root/subA/a2.txt
...

2023-03-20 15:45 UTC, f-lab-paca commented on app/src/main/java/com/example/designpatternstudy/Composite/Folder.kt
> +        return data
`sum` 함수가 호출될때마다 data property가 증가하는데 의도하신걸까요?

2023-03-21 06:54 UTC, honggi123 commented on app/src/main/java/com/example/designpatternstudy/Composite/Folder.kt
> +        return data
sum() 함수는 모든 하위 클래스들의 data값을 더해서 반환주려고 했고
data property가 반복되어 증가되는 것은 의도하지 않았네요 수정해야할것 같습니다

2023-03-21 13:33 UTC, ColaGom commented on app/src/main/java/com/example/designpatternstudy/Composite/FolderComponent.kt
> +}
```suggestion
interface FolderComponent {
    val name : String
    fun print()
}
```

2023-03-22 04:45 UTC, merged